const $=(s,el=document)=>el.querySelector(s);const $$=(s,el=document)=>[...el.querySelectorAll(s)];
const lessons={"Lesson 1":"Location, importance, core/periphery and economic structure","Lesson 2":"Trade, aid, inequality, geopolitics and technology","Lesson 3":"Rapid development, Shell and development strategies","Final":"Exam practice and final retrieval"};
const norm=s=>(s||'').toString().toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9.#]+/g,' ').trim();
const doneKey=id=>'nigeriaquest_done_'+id;const scoreKey=()=> 'nigeriaquest_score';
let points=Number(localStorage.getItem(scoreKey())||0);
function isDone(id){return localStorage.getItem(doneKey(id))==='1'}
function setDone(id){if(!isDone(id)){localStorage.setItem(doneKey(id),'1');points+=50;localStorage.setItem(scoreKey(),points)} updateProgress(); buildMap();}
function pct(){return Math.round((ACTIVITIES.filter(a=>isDone(a.id)).length/ACTIVITIES.length)*100)}
function updateProgress(){const p=pct(); $('#heroScore').textContent=p+'%'; $('#heroBar').style.width=p+'%'; const count=ACTIVITIES.filter(a=>isDone(a.id)).length; $('#badgeLine').textContent=count===0?'No badges unlocked yet.':`${count}/${ACTIVITIES.length} activities complete • ${points} XP`;}
function buildTabs(){const nav=$('#lessonTabs'); nav.innerHTML=Object.keys(lessons).map(l=>`<a href="#${l.replace(/ /g,'-')}">${l}</a>`).join('')+`<a href="#game-hub">Games</a>`}
function buildMap(){const map=$('#quest-map'); map.innerHTML=''; Object.entries(lessons).forEach(([lesson,desc])=>{let acts=ACTIVITIES.filter(a=>a.lesson===lesson); if(!acts.length)return; map.insertAdjacentHTML('beforeend',`<section class="lesson-block" id="${lesson.replace(/ /g,'-')}"><div class="lesson-title"><div><p>${desc}</p><h2>${lesson}</h2></div><span class="badge">${acts.filter(a=>isDone(a.id)).length}/${acts.length} complete</span></div><div class="activity-grid">${acts.map(a=>`<button class="activity-card ${isDone(a.id)?'done':''}" data-id="${a.id}" data-lesson="${a.lesson}"><span class="badge">${labelType(a.type)}</span><h3>${a.title}</h3><p>${a.description||''}</p></button>`).join('')}</div></section>`)}); $$('.activity-card').forEach(b=>b.addEventListener('click',()=>openActivity(b.dataset.id))); updateProgress();}
function labelType(t){return {short:'Retrieval race',writing:'Exam dojo',table:'Grid unlock',sort:'Sorting arena',sortwrite:'Sort + write',gapfill:'Codebreaker',datawriting:'Data detective',exit:'Exit ticket'}[t]||t}
function head(a){return `<article class="activity" id="active-${a.id}"><div class="activity-head"><div class="progress-strip"><span class="chip-small">${a.lesson}</span><span class="chip-small">${labelType(a.type)}</span><span class="chip-small">+50 XP</span></div><h2>${a.title}</h2><p>${a.description||''}</p></div><div class="activity-body">`}
function foot(a){return `<div class="btnrow"><button class="btn teal" onclick="setDone('${a.id}')">Mark this activity complete</button><button class="btn secondary" onclick="buildMap();$('#activityStage').innerHTML=''">Back to quest map</button></div></div></article>`}
function openActivity(id){const a=ACTIVITIES.find(x=>x.id===id); let html=''; if(a.type==='short')html=renderShort(a); if(a.type==='writing')html=renderWriting(a); if(a.type==='table')html=renderTable(a); if(a.type==='sort'||a.type==='sortwrite')html=renderSort(a); if(a.type==='gapfill')html=renderGap(a); if(a.type==='datawriting')html=renderData(a); if(a.type==='exit')html=renderExit(a); $('#activityStage').innerHTML=html; setupDrag(); location.hash='activityStage';}
function renderShort(a){return head(a)+`<div class="qcard"><h3>Retrieval race</h3><p>Answer the questions, then hit check. Close spelling is fine where the key idea is clear.</p></div><div class="grid">${a.questions.map((q,i)=>`<div class="qcard"><label>${i+1}. ${q[0]}</label><input id="${a.id}_${i}" autocomplete="off"><div id="${a.id}_f${i}" class="feedback hidden"></div></div>`).join('')}</div>${a.challenge?`<div class="qcard"><label>Challenge</label><textarea placeholder="${a.challenge}"></textarea></div>`:''}<div class="btnrow"><button class="btn" onclick="checkShort('${a.id}')">Check answers</button><button class="btn secondary" onclick="toggle('${a.id}_ans')">Reveal answer key</button></div><div class="answers" id="${a.id}_ans"><h3>Answer key</h3><ol>${a.answers.map(x=>`<li>${x}</li>`).join('')}</ol></div>`+foot(a)}
function checkShort(id){const a=ACTIVITIES.find(x=>x.id===id);let c=0;a.questions.forEach((q,i)=>{const val=norm($('#'+id+'_'+i).value); let needed=q[2]||1; let hits=q[1].filter(ans=>val.includes(norm(ans))).length; let ok=hits>=needed; if(q[2]) ok=q[1].filter(ans=>val.includes(norm(ans))).length>=q[2]; const f=$('#'+id+'_f'+i); f.classList.remove('hidden'); f.className='feedback '+(ok?'correct':'wrong'); f.textContent=ok?'Correct.':'Not quite. Improve it, or reveal the answer key after trying.'; if(ok)c++;}); toast(`${c}/${a.questions.length} correct`); if(c===a.questions.length)setDone(id)}
function renderWriting(a){return head(a)+`<div class="qcard"><h3>Exam dojo</h3><p>Write an answer, tick the success criteria you have included, then reveal the model to improve it.</p></div><div class="grid">${a.prompts.map((p,i)=>`<div class="qcard"><span class="pill">${p.marks} marks</span><label>${p.q}</label><textarea id="${a.id}_w${i}" placeholder="Write your exam answer here..."></textarea><div class="checklist">${p.checks.map((c,j)=>`<label><input type="checkbox" class="${a.id}_chk${i}"> ${c}</label>`).join('')}</div><div class="feedback" id="${a.id}_score${i}">Tick your success criteria to estimate your mark.</div><div class="btnrow"><button class="btn" onclick="scoreWriting('${a.id}',${i})">Estimate mark</button><button class="btn secondary" onclick="toggle('${a.id}_model${i}')">Reveal model</button></div><div class="answers" id="${a.id}_model${i}"><p>${p.model}</p></div></div>`).join('')}</div>`+foot(a)}
function scoreWriting(id,i){const a=ACTIVITIES.find(x=>x.id===id), p=a.prompts[i]; const checks=$$('.'+id+'_chk'+i); const hit=checks.filter(c=>c.checked).length; const est=Math.min(p.marks,Math.round(hit/checks.length*p.marks)); $('#'+id+'_score'+i).textContent=`Estimated mark: ${est}/${p.marks}. Now add anything missing before revealing the model.`; if(est===p.marks) points+=5, localStorage.setItem(scoreKey(),points), updateProgress();}
function renderTable(a){const multi=!!a.columns; let body;if(multi){body=`<table class="table"><thead><tr>${a.columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${a.rows.map((r,i)=>`<tr><td><b>${r[0]}</b></td>${r.slice(1).map((_,j)=>`<td><input class="table-input" id="${a.id}_${i}_${j}"></td>`).join('')}</tr>`).join('')}</tbody></table>`}else{body=`<table class="table"><thead><tr><th>Prompt</th><th>Your answer</th></tr></thead><tbody>${a.rows.map((r,i)=>`<tr><td><b>${r[0]}</b></td><td><input class="table-input" id="${a.id}_${i}"></td></tr>`).join('')}</tbody></table>`} const ans=`<table class="table"><tbody>${a.rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;return head(a)+`<div class="qcard"><h3>Grid unlock</h3><p>Complete the grid. Aim for precise case study language.</p></div>${body}${a.stretch?`<div class="qcard"><label>Stretch</label><textarea placeholder="${a.stretch}"></textarea></div>`:''}<div class="btnrow"><button class="btn" onclick="checkTable('${a.id}')">Check grid</button><button class="btn secondary" onclick="toggle('${a.id}_ans')">Reveal completed grid</button></div><div class="answers" id="${a.id}_ans">${ans}</div>`+foot(a)}
function fuzzy(val,ans){val=norm(val); ans=norm(ans); if(val.includes(ans)||ans.includes(val)&&val.length>3)return true; return ans.split(' ').some(w=>w.length>4&&val.includes(w))}
function checkTable(id){const a=ACTIVITIES.find(x=>x.id===id);let total=0,hit=0;if(a.columns){a.rows.forEach((r,i)=>r.slice(1).forEach((ans,j)=>{total++; if(fuzzy($('#'+id+'_'+i+'_'+j).value,ans))hit++;}))}else{a.rows.forEach((r,i)=>{total++; if(fuzzy($('#'+id+'_'+i).value,r[1]))hit++;})}toast(`Grid check: about ${hit}/${total} matched. Reveal the grid to improve any missing detail.`); if(hit>=Math.ceil(total*.75))setDone(id)}
function renderSort(a){return head(a)+`<div class="qcard"><h3>Sorting arena</h3><p>Drag each card into the correct category. Cards turn green or red when checked.</p></div><div class="sort-wrap"><div class="item-bank"><h3>Mixed options</h3><div class="bank">${Object.keys(a.items).sort(()=>Math.random()-.5).map(it=>`<span draggable="true" class="chip" data-item="${it}">${it}</span>`).join('')}</div></div><div class="dropzones">${a.categories.map(c=>`<div class="dropzone" data-cat="${c}"><h3>${c}</h3></div>`).join('')}</div></div>${a.challenge?`<div class="qcard"><label>Challenge</label><textarea placeholder="${a.challenge}"></textarea></div>`:''}<div class="btnrow"><button class="btn" onclick="checkSort('${a.id}')">Check sort</button><button class="btn secondary" onclick="resetSort('${a.id}')">Reset</button></div><div id="${a.id}_feedback" class="feedback hidden"></div>${a.prompts?miniPrompts(a):''}`+foot(a)}
function miniPrompts(a){return `<div class="grid">${a.prompts.map((p,i)=>`<div class="qcard"><span class="pill">${p.marks} marks</span><label>${p.q}</label><textarea></textarea><button class="btn secondary" onclick="toggle('${a.id}_model${i}')">Reveal model</button><div class="answers" id="${a.id}_model${i}"><p>${p.model}</p><ul>${p.checks.map(c=>`<li>${c}</li>`).join('')}</ul></div></div>`).join('')}</div>`}
function setupDrag(){document.addEventListener('dragstart',e=>{if(e.target.classList.contains('chip'))e.dataTransfer.setData('text/plain',e.target.dataset.item)});document.addEventListener('dragover',e=>{if(e.target.closest('.dropzone')||e.target.closest('.bank'))e.preventDefault()});document.addEventListener('drop',e=>{let z=e.target.closest('.dropzone')||e.target.closest('.bank');if(!z)return;e.preventDefault();let item=e.dataTransfer.getData('text/plain');let chip=$(`.chip[data-item="${CSS.escape(item)}"]`);if(chip)z.appendChild(chip)})}
function checkSort(id){const a=ACTIVITIES.find(x=>x.id===id);let total=Object.keys(a.items).length,hit=0;$$(`#active-${id} .chip`).forEach(ch=>{const zone=ch.closest('.dropzone'); ch.classList.remove('correct-chip','wrong-chip'); if(zone){if(a.items[ch.dataset.item]===zone.dataset.cat){hit++;ch.classList.add('correct-chip')}else ch.classList.add('wrong-chip')}});let f=$('#'+id+'_feedback');f.classList.remove('hidden');f.className='feedback '+(hit===total?'correct':'wrong');f.textContent=`${hit}/${total} correct.`; if(hit===total)setDone(id)}
function resetSort(id){const bank=$(`#active-${id} .bank`);$$(`#active-${id} .chip`).forEach(c=>{c.classList.remove('correct-chip','wrong-chip');bank.appendChild(c)})}
function renderGap(a){let para=a.paragraph.replace(/\[gap(\d+)\]/g,(m,n)=>`<select class="gap-select" id="${a.id}_gap${n}"><option value="">Choose...</option>${a.options.map(o=>`<option>${o}</option>`).join('')}</select>`);return head(a)+`<div class="qcard"><h3>Codebreaker</h3><p>Crack the paragraph by choosing the correct evidence for each gap.</p></div><div class="paragraph">${para}</div><div class="btnrow"><button class="btn" onclick="checkGap('${a.id}')">Check code</button><button class="btn secondary" onclick="toggle('${a.id}_ans')">Reveal completed paragraph</button></div><div id="${a.id}_feedback" class="feedback hidden"></div><div class="answers" id="${a.id}_ans"><p>${a.paragraph.replace(/\[gap(\d+)\]/g,(m,n)=>`<b>${a.answers[n]}</b>`)}</p><p><b>Why it matters:</b> ${a.why}</p></div>`+foot(a)}
function checkGap(id){const a=ACTIVITIES.find(x=>x.id===id);let hit=0;a.answers.forEach((ans,i)=>{let el=$('#'+id+'_gap'+i);let ok=el.value===ans;el.style.borderColor=ok?'var(--good)':'var(--bad)';if(ok)hit++});let f=$('#'+id+'_feedback');f.classList.remove('hidden');f.className='feedback '+(hit===a.answers.length?'correct':'wrong');f.textContent=`${hit}/${a.answers.length} correct.`; if(hit===a.answers.length)setDone(id)}
function renderData(a){return head(a)+`<div class="qcard"><h3>Data detective</h3><p>Use the evidence table, solve the calculation, then complete the exam-style explanations.</p></div><div class="data-box"><table class="table"><tbody>${a.data.map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td></tr>`).join('')}</tbody></table></div><div class="qcard"><label>${a.calc.q}</label><input id="${a.id}_calc" placeholder="Show your working"><div id="${a.id}_calcf" class="feedback hidden"></div></div><button class="btn" onclick="checkCalc('${a.id}')">Check calculation</button>`+renderWriting(a).replace(head(a),'').replace(foot(a),'')+`<div class="answers" id="${a.id}_ans"><p><b>Calculation:</b> $55.6bn - $52.4bn = +$3.2bn, so Nigeria has a trade surplus.</p></div>`+foot(a)}
function checkCalc(id){let ok=norm($('#'+id+'_calc').value).includes('3.2');let f=$('#'+id+'_calcf');f.classList.remove('hidden');f.className='feedback '+(ok?'correct':'wrong');f.textContent=ok?'Correct: +$3.2bn trade surplus.':'Try exports minus imports: 55.6 - 52.4.'; if(ok)points+=5,localStorage.setItem(scoreKey(),points),updateProgress()}
function renderExit(a){return head(a)+`<div class="qcard"><h3>Final retrieval grid</h3><p>Add one accurate fact for each area. Then compare with the suggestions.</p></div><table class="table"><thead><tr><th>Area</th><th>One accurate fact</th></tr></thead><tbody>${a.areas.map((x,i)=>`<tr><td><b>${x}</b></td><td><input class="table-input"></td></tr>`).join('')}</tbody></table><button class="btn secondary" onclick="toggle('${a.id}_ans')">Show suggested facts</button><div class="answers" id="${a.id}_ans"><ul>${a.suggestions.map(s=>`<li>${s}</li>`).join('')}</ul></div>`+foot(a)}
function toggle(id){$('#'+id).classList.toggle('show')}
function toast(msg){let t=document.createElement('div');t.className='feedback correct';t.style.position='fixed';t.style.right='18px';t.style.bottom='18px';t.style.zIndex='99';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2300)}
function questionBank(){let qs=[];ACTIVITIES.forEach(a=>{if(a.type==='short')a.questions.forEach((q,i)=>qs.push({q:q[0],a:a.answers[i],keys:q[1]})); if(a.type==='table'&&!a.columns)a.rows.forEach(r=>qs.push({q:r[0],a:r[1],keys:[r[1]]})); if(a.type==='gapfill')a.answers.forEach((ans,i)=>qs.push({q:`Technology gap ${i+1}`,a:ans,keys:[ans]}));});return qs.sort(()=>Math.random()-.5)}
function openGame(mode){const stage=$('#gameStage');stage.classList.remove('hidden');location.hash='gameStage'; if(mode==='dash')gameDash(stage); if(mode==='flash')gameFlash(stage); if(mode==='match')gameMatch(stage); if(mode==='boss')gameBoss(stage)}
function gameDash(stage){const qs=questionBank().slice(0,10);stage.innerHTML=`<h2>Nigeria Dash</h2><p>Answer 10 rapid questions. Beat your previous score.</p><div id="dashBox"></div><div class="btnrow"><button class="btn" id="dashCheck">Check dash</button><button class="btn secondary" onclick="$('#gameStage').classList.add('hidden')">Close</button></div>`;$('#dashBox').innerHTML=qs.map((q,i)=>`<div class="qcard"><label>${i+1}. ${q.q}</label><input id="dash${i}"><div id="dashf${i}" class="feedback hidden"></div></div>`).join('');$('#dashCheck').onclick=()=>{let hit=0;qs.forEach((q,i)=>{let ok=q.keys.some(k=>norm($('#dash'+i).value).includes(norm(k)));let f=$('#dashf'+i);f.classList.remove('hidden');f.className='feedback '+(ok?'correct':'wrong');f.textContent=ok?'Correct.':`Answer: ${q.a}`;if(ok)hit++});points+=hit*3;localStorage.setItem(scoreKey(),points);updateProgress();toast(`Dash score: ${hit}/10`)};}
function gameFlash(stage){const qs=questionBank();let i=0;function draw(){let q=qs[i%qs.length];stage.innerHTML=`<h2>Flashcard Flip</h2><div class="flashcard"><div><p class="eyebrow dark">Card ${i+1} of ${qs.length}</p><h3>${q.q}</h3><div class="answers" id="flashAns"><h3>${q.a}</h3></div></div></div><div class="btnrow"><button class="btn" onclick="toggle('flashAns')">Flip card</button><button class="btn teal" id="knowBtn">I knew it</button><button class="btn secondary" id="nextBtn">Next</button><button class="btn secondary" onclick="$('#gameStage').classList.add('hidden')">Close</button></div>`;$('#nextBtn').onclick=()=>{i++;draw()};$('#knowBtn').onclick=()=>{points+=2;localStorage.setItem(scoreKey(),points);updateProgress();toast('+2 XP');i++;draw()}}draw()}
function gameMatch(stage){const qs=questionBank().slice(0,6);let left=qs.map((q,i)=>({text:q.q,id:i})).sort(()=>Math.random()-.5), right=qs.map((q,i)=>({text:q.a,id:i})).sort(()=>Math.random()-.5), selected=null,matched=new Set();stage.innerHTML=`<h2>Fact Match</h2><p>Match each prompt to its correct answer.</p><div class="match-grid"><div class="match-col" id="matchL"></div><div class="match-col" id="matchR"></div></div><div class="btnrow"><button class="btn secondary" onclick="$('#gameStage').classList.add('hidden')">Close</button></div>`;function draw(){ $('#matchL').innerHTML=left.map(x=>`<button class="match-item ${matched.has(x.id)?'matched':''}" data-side="l" data-id="${x.id}">${x.text}</button>`).join(''); $('#matchR').innerHTML=right.map(x=>`<button class="match-item ${matched.has(x.id)?'matched':''}" data-side="r" data-id="${x.id}">${x.text}</button>`).join(''); $$('.match-item').forEach(b=>b.onclick=()=>{if(b.classList.contains('matched'))return; if(!selected){selected=b;b.classList.add('selected');return} if(selected.dataset.side!==b.dataset.side && selected.dataset.id===b.dataset.id){matched.add(Number(b.dataset.id));points+=5;localStorage.setItem(scoreKey(),points);updateProgress();toast('Matched +5 XP');selected=null;draw(); if(matched.size===qs.length)toast('Fact Match complete!')} else {selected.classList.remove('selected');selected=null;toast('Try another match.')}})}draw()}
function gameBoss(stage){let prompts=[];ACTIVITIES.filter(a=>a.prompts).forEach(a=>a.prompts.filter(p=>p.marks>=8).forEach(p=>prompts.push(p)));if(!prompts.length)prompts=ACTIVITIES.find(a=>a.id==='final-practice').prompts;let p=prompts[Math.floor(Math.random()*prompts.length)];stage.innerHTML=`<h2>8-Mark Boss Battle</h2><p>Build a plan before writing. Tick the evidence you have included, then reveal the model points.</p><div class="qcard"><span class="pill">${p.marks||8} marks</span><label>${p.q}</label><textarea placeholder="Plan: point 1, point 2, point 3, judgement..."></textarea><div class="checklist">${(p.checks||[]).map(c=>`<label><input type="checkbox"> ${c}</label>`).join('')}</div><button class="btn secondary" onclick="toggle('bossModel')">Reveal boss hints</button><div class="answers" id="bossModel"><p>${p.model}</p></div></div><div class="btnrow"><button class="btn teal" onclick="points+=25;localStorage.setItem(scoreKey(),points);updateProgress();toast('Boss battle complete +25 XP')">Complete boss battle</button><button class="btn secondary" onclick="openGame('boss')">New boss question</button><button class="btn secondary" onclick="$('#gameStage').classList.add('hidden')">Close</button></div>`}
$('#quickPlayBtn').onclick=()=>openGame('dash');$$('.game-card').forEach(b=>b.onclick=()=>openGame(b.dataset.mode));$('#resetBtn').onclick=()=>{if(confirm('Reset saved progress on this device?')){Object.keys(localStorage).filter(k=>k.startsWith('nigeriaquest_')).forEach(k=>localStorage.removeItem(k));points=0;buildMap();updateProgress();}};
buildTabs();buildMap();updateProgress();
