
const app=document.getElementById('app'); const menu=document.getElementById('menu');
const norm=s=>(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9%#\. ]/g,' ').replace(/\s+/g,' ').trim();
const save=(id,val)=>localStorage.setItem('nigeria_'+id, JSON.stringify(val));
const load=id=>{try{return JSON.parse(localStorage.getItem('nigeria_'+id)||'null')}catch(e){return null}};
function markDone(id){save('done_'+id,true); updateProgress();}
function updateProgress(){let done=ACTIVITIES.filter(a=>load('done_'+a.id)).length; document.querySelectorAll('.progress span').forEach(x=>x.style.width=(done/ACTIVITIES.length*100)+'%'); document.querySelectorAll('.progText').forEach(x=>x.textContent=`${done}/${ACTIVITIES.length} activities completed`)}
function makeMenu(){ACTIVITIES.forEach(a=>{let link=document.createElement('a');link.href='#'+a.id;link.innerHTML=`${a.lesson}: ${a.title}<small>${a.description}</small>`;menu.appendChild(link)})}
function sectionShell(a,inner){return `<section class="activity" id="${a.id}"><a class="toplink" href="#menu">Main menu ↑</a><span class="meta">${a.lesson}</span><h2>${a.title}</h2><p class="desc">${a.description}</p>${inner}<div class="progress"><span></span></div><p class="progText"></p></section>`}
function renderShort(a){let qs=a.questions.map((q,i)=>`<div class="qcard"><label>${i+1}. ${q[0]}</label><input id="${a.id}_q${i}" autocomplete="off"><div id="${a.id}_f${i}" class="feedback"></div></div>`).join('');let ans='<ol>'+a.answers.map(x=>`<li>${x}</li>`).join('')+'</ol>';let challenge=a.challenge?`<div class="qcard"><label>Challenge</label><textarea placeholder="${a.challenge}"></textarea></div>`:'';return sectionShell(a,`<div class="grid two">${qs}</div>${challenge}<div class="btnrow"><button class="btn" onclick="checkShort('${a.id}')">Check answers</button><button class="btn secondary" onclick="toggleAnswers('${a.id}')">Show full answers</button></div><div class="answers" id="${a.id}_answers"><h3>Answers</h3>${ans}</div>`)}
function checkShort(id){let a=ACTIVITIES.find(x=>x.id==id), total=0; a.questions.forEach((q,i)=>{let val=norm(document.getElementById(`${id}_q${i}`).value);let needed=q[2]||1;let hits=q[1].filter(k=>val.includes(norm(k))).length;let ok=hits>=needed; total+=ok; let f=document.getElementById(`${id}_f${i}`); f.className='feedback '+(ok?'correct':'wrong'); f.textContent=ok?'Correct':'Check this one, then compare with the answer list.';}); if(total===a.questions.length) markDone(id)}
function renderWriting(a){let cards=a.prompts.map((p,i)=>`<div class="qcard"><p><span class="pill">${p.marks} marks</span></p><label>${p.q}</label><textarea id="${a.id}_w${i}" placeholder="Write your answer here..."></textarea><div class="checklist">${p.checks.map((c,j)=>`<label><input type="checkbox" class="${a.id}_chk${i}"> ${c}</label>`).join('')}</div><div class="scorebox" id="${a.id}_score${i}">Self-assess using the checklist, then reveal the model.</div><button class="btn teal" onclick="scoreWriting('${a.id}',${i})">Update self-mark</button><button class="btn secondary" onclick="toggleOne('${a.id}_model${i}')">Reveal model answer / planning points</button><div class="answers" id="${a.id}_model${i}"><h3>Model answer / planning points</h3><p>${p.model}</p></div></div>`).join('');return sectionShell(a,`<div class="grid">${cards}</div><div class="btnrow"><button class="btn" onclick="markDone('${a.id}')">Mark activity as complete</button></div>`)}
function scoreWriting(id,i){let checks=[...document.querySelectorAll(`.${id}_chk${i}`)];let hit=checks.filter(c=>c.checked).length;let marks=ACTIVITIES.find(a=>a.id==id).prompts[i].marks;let est=Math.min(marks, Math.round(hit/checks.length*marks));document.getElementById(`${id}_score${i}`).textContent=`Estimated self-mark: ${est}/${marks}. Add missing checklist points before moving on.`}
function renderTable(a){let isMulti=!!a.columns;let body;if(isMulti){body=`<table class="table"><thead><tr>${a.columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${a.rows.map((r,i)=>`<tr><td>${r[0]}</td>${r.slice(1).map((_,j)=>`<td><input class="table-input" id="${a.id}_${i}_${j}"></td>`).join('')}</tr>`).join('')}</tbody></table>`}else{body=`<table class="table"><thead><tr><th>Prompt</th><th>Your answer</th></tr></thead><tbody>${a.rows.map((r,i)=>`<tr><td><strong>${r[0]}</strong></td><td><input class="table-input" id="${a.id}_${i}"></td></tr>`).join('')}</tbody></table>`}let ans=`<table class="table"><tbody>${a.rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;return sectionShell(a,`${body}${a.stretch?`<div class="qcard"><label>Stretch</label><textarea placeholder="${a.stretch}"></textarea></div>`:''}<div class="btnrow"><button class="btn" onclick="checkTable('${a.id}')">Check table</button><button class="btn secondary" onclick="toggleAnswers('${a.id}')">Show answer table</button></div><div class="answers" id="${a.id}_answers"><h3>Answer table</h3>${ans}</div>`)}
function checkTable(id){let a=ACTIVITIES.find(x=>x.id==id), cells=0, hits=0;if(a.columns){a.rows.forEach((r,i)=>r.slice(1).forEach((ans,j)=>{cells++; let val=norm(document.getElementById(`${id}_${i}_${j}`).value); if(ans.split(/,|\/|;| and /).some(part=>val.includes(norm(part).split(' ')[0]) && norm(part).split(' ')[0].length>2) || val.includes(norm(ans))) hits++;}))}else{a.rows.forEach((r,i)=>{cells++; let val=norm(document.getElementById(`${id}_${i}`).value); let ans=norm(r[1]); if(ans.split(' ').some(w=>w.length>4 && val.includes(w)) || val.includes(ans)) hits++;})} alert(`You matched about ${hits}/${cells}. Use the answer table to improve any missing detail.`); if(hits>=Math.ceil(cells*.7)) markDone(id)}
function renderSort(a){let items=Object.keys(a.items).sort(()=>Math.random()-.5).map(it=>`<span draggable="true" class="chip" data-item="${it}">${it}</span>`).join('');let zones=a.categories.map(c=>`<div class="dropzone" data-cat="${c}"><h3>${c}</h3></div>`).join('');let extra=a.prompts?renderPromptMini(a):'';return sectionShell(a,`<div class="sort-wrap"><div class="item-bank"><h3>Mixed options</h3><div class="bank">${items}</div></div><div class="dropzones">${zones}</div></div>${a.challenge?`<div class="qcard"><label>Challenge</label><textarea placeholder="${a.challenge}"></textarea></div>`:''}<div class="btnrow"><button class="btn" onclick="checkSort('${a.id}')">Check sort</button><button class="btn secondary" onclick="resetSort('${a.id}')">Reset sort</button></div><div id="${a.id}_sortfeedback" class="feedback"></div>${extra}`)}
function renderPromptMini(a){return `<div class="grid">${a.prompts.map((p,i)=>`<div class="qcard"><p><span class="pill">${p.marks} marks</span></p><label>${p.q}</label><textarea></textarea><button class="btn secondary" onclick="toggleOne('${a.id}_model${i}')">Reveal model</button><div class="answers" id="${a.id}_model${i}"><p>${p.model}</p><ul>${p.checks.map(c=>`<li>${c}</li>`).join('')}</ul></div></div>`).join('')}</div>`}
function setupDrag(){document.addEventListener('dragstart',e=>{if(e.target.classList.contains('chip'))e.dataTransfer.setData('text/plain',e.target.dataset.item)});document.addEventListener('dragover',e=>{if(e.target.closest('.dropzone')||e.target.closest('.bank'))e.preventDefault();});document.addEventListener('drop',e=>{let z=e.target.closest('.dropzone')||e.target.closest('.bank');if(!z)return; e.preventDefault();let item=e.dataTransfer.getData('text/plain');let chip=document.querySelector(`.chip[data-item="${CSS.escape(item)}"]`); if(chip)z.appendChild(chip);});}
function checkSort(id){let a=ACTIVITIES.find(x=>x.id==id), total=0, correct=0;document.querySelectorAll(`#${id} .dropzone`).forEach(z=>{let cat=z.dataset.cat;[...z.querySelectorAll('.chip')].forEach(ch=>{total++; if(a.items[ch.dataset.item]===cat) correct++;})});let f=document.getElementById(`${id}_sortfeedback`);f.className='feedback '+(correct===Object.keys(a.items).length?'correct':'wrong');f.textContent=`${correct}/${Object.keys(a.items).length} correct. ${correct===Object.keys(a.items).length?'Excellent.':'Move any that need improving and check again.'}`;if(correct===Object.keys(a.items).length)markDone(id)}
function resetSort(id){let bank=document.querySelector(`#${id} .bank`);document.querySelectorAll(`#${id} .chip`).forEach(c=>bank.appendChild(c));}
function renderGap(a){let para=a.paragraph.replace(/\[gap(\d+)\]/g,(m,n)=>`<select class="gap-select" id="${a.id}_gap${n}"><option value="">Choose...</option>${a.options.map(o=>`<option>${o}</option>`).join('')}</select>`);return sectionShell(a,`<div class="paragraph">${para}</div><div class="btnrow"><button class="btn" onclick="checkGap('${a.id}')">Check gap fill</button><button class="btn secondary" onclick="toggleAnswers('${a.id}')">Show completed answer</button></div><div id="${a.id}_gapfeedback" class="feedback"></div><div class="answers" id="${a.id}_answers"><h3>Completed answer</h3><p>${a.paragraph.replace(/\[gap(\d+)\]/g,(m,n)=>`<strong>${a.answers[n]}</strong>`)}</p><p><strong>Why it matters:</strong> ${a.why}</p></div>`)}
function checkGap(id){let a=ACTIVITIES.find(x=>x.id==id), c=0;a.answers.forEach((ans,i)=>{let el=document.getElementById(`${id}_gap${i}`);let ok=el.value===ans;el.style.borderColor=ok?'var(--ok)':'var(--bad)'; if(ok)c++;});let f=document.getElementById(`${id}_gapfeedback`);f.className='feedback '+(c===a.answers.length?'correct':'wrong');f.textContent=`${c}/${a.answers.length} correct.`;if(c===a.answers.length)markDone(id)}
function renderDataWriting(a){let data=`<div class="data-box"><table class="table"><tbody>${a.data.map(r=>`<tr><td>${r[0]}</td><td><strong>${r[1]}</strong></td></tr>`).join('')}</tbody></table></div>`;let calc=`<div class="qcard"><label>${a.calc.q}</label><input id="${a.id}_calc" placeholder="e.g. 55.6 - 52.4 = +3.2"><div id="${a.id}_calcf" class="feedback"></div></div>`;return sectionShell(a,`${data}${calc}<div class="btnrow"><button class="btn" onclick="checkCalc('${a.id}')">Check calculation</button></div>${renderWriting(a).match(/<div class="grid">[\s\S]*?<\/div><div class="btnrow">/)[0].replace('<div class="btnrow">','')}<div class="answers" id="${a.id}_answers"><p><strong>Calculation:</strong> $55.6bn – $52.4bn = +$3.2bn, so Nigeria has a trade surplus.</p></div>`)}
function checkCalc(id){let val=norm(document.getElementById(`${id}_calc`).value);let ok=val.includes('3.2')||val.includes('+3.2');let f=document.getElementById(`${id}_calcf`);f.className='feedback '+(ok?'correct':'wrong');f.textContent=ok?'Correct: +$3.2bn trade surplus.':'Check: exports minus imports = 55.6 - 52.4.'; if(ok) markDone(id)}
function renderExit(a){let rows=a.areas.map((area,i)=>`<tr><td><strong>${area}</strong></td><td><input class="table-input" id="${a.id}_${i}"></td></tr>`).join('');let suggestions='<ul>'+a.suggestions.map(s=>`<li>${s}</li>`).join('')+'</ul>';return sectionShell(a,`<table class="table"><thead><tr><th>Area</th><th>One accurate fact</th></tr></thead><tbody>${rows}</tbody></table><div class="btnrow"><button class="btn" onclick="markDone('${a.id}')">Mark complete</button><button class="btn secondary" onclick="toggleAnswers('${a.id}')">Show suggested facts</button></div><div class="answers" id="${a.id}_answers">${suggestions}</div>`)}
function toggleAnswers(id){document.getElementById(id+'_answers').classList.toggle('show')}
function toggleOne(id){document.getElementById(id).classList.toggle('show')}
function render(){makeMenu();let lessons=['Lesson 1','Lesson 2','Lesson 3','Final'];lessons.forEach(l=>{let acts=ACTIVITIES.filter(a=>a.lesson===l);if(!acts.length)return;app.insertAdjacentHTML('beforeend',`<section class="lesson-intro"><h2>${l}</h2><p class="desc">${l==='Lesson 1'?'Location, importance, core/periphery and economic structure':l==='Lesson 2'?'Trade, aid, inequality, geopolitics and technology':l==='Lesson 3'?'Rapid development, Shell and development strategies':'Exam practice and final retrieval'}</p></section>`);acts.forEach(a=>{let html=''; if(a.type==='short')html=renderShort(a); if(a.type==='writing')html=renderWriting(a); if(a.type==='table')html=renderTable(a); if(a.type==='sort')html=renderSort(a); if(a.type==='sortwrite')html=renderSort(a); if(a.type==='gapfill')html=renderGap(a); if(a.type==='datawriting')html=renderDataWriting(a); if(a.type==='exit')html=renderExit(a); app.insertAdjacentHTML('beforeend',html);});});setupDrag();updateProgress();}
document.getElementById('resetAll').addEventListener('click',()=>{if(confirm('Reset all saved progress on this device?')){Object.keys(localStorage).filter(k=>k.startsWith('nigeria_')).forEach(k=>localStorage.removeItem(k));location.reload();}});render();
